### ISSUE TITLE
Create API and react routes

### ISSUE THREAD

**Issue by riceball1** [bayareawebdevs/reduce-food-waste-app#4]
Initial react-router routes and API should be created to begin navigating a simple app

**Tips for working collaboratively:** 
- Fork the repo and work on your own branch for the feature you are adding
- Make sure to do ```git fetch``` to see if there are any changes to ```git log``` when on your local repo
- ```git merge``` any changes and fix any conflicts
- ```git commit``` small commits (avoid doing too many large changes)

**Task List**
- [ ] Landing page @mulana 
- [ ] Signin/Login page (JWT?) @mrmojica 
- [ ]  Profile
- [ ]Server and Models (Database using MongoDB and mLab) @riceball1

**Comment by riceball1** [comment]
@mulana do you want to start by creating a branch and making a page for signin/login? You will want to use React, if not start with a basic html form.

**Comment by mrmojica** [comment]
That works for me I'll probably use passport as well maybe.

Thanks,

Michael

**Comment by riceball1** [comment]
@mrmojica - awesome, if Michael you want to set up the login page, maybe @mulana (Ana) you can look at his code to maybe build a landing page then?

**Comment by riceball1** [comment]
@mrmojica - what about using Passportjs and JWT token? Have you done that? I've heard it was better for mobile. You might not even need passportjs if you use jwt token.

**Comment by mulana** [comment]
Dana @riceball1 thanks for adding me to the project. 
That works for me: I'll play with the project first and then I should be able to continue to the landing page.

**Comment by riceball1** [comment]
@mrmojica @mulana - I just sent a pull request for the

**Comment by riceball1** [comment]
@mrmojica @mulana - I just merged changes into the models branch that allows for a user to be created, deleted, updated and users to be retrieved. Please checkout this link for a live version of the site: [click link here](https://reduce-food-waste.herokuapp.com/ ) . Please add "data/users" to the url to retrieve users data (you can check out the server/routes files to see the endpoints).
